apiVersion: v3.1.0 # Standard version
kind: DataContract

id: 05E75EB8-7138-47B0-A5E9-81D08B4154C7
name: sp500_nasdaq100_2025
version: 0.0.1 # Data Contract Version
status: draft # proposed", "draft", "active", "deprecated", "retired"
domain: study
dataProduct: sp500_nasdaq100_2025
tenant: jtviegas

description:
  purpose: price data for S&P 500 and NASDAQ 100 for the year 2025
  # limitations: Cannot be used in conjunction with days with full moons.
  # usage: Twice a day, preferable before meals.
  # customProperties: ... not part of the standard

tags: ['finance'] # finance, sensitive, employee_record.

schema:
  - id: sp500_nasdaq100_2025_obj
    name: sp500_nasdaq100_2025
    logicalType: object
    physicalType: file
    physicalName: sp500_nasdaq100_2025
    description: provides price data for a ticker in the S&P 500 and NASDAQ 100 on a specific day in the year 2025
    dataGranularityDescription: Aggregation on columns txn_ref_dt, pmt_txn_id
    # quality: ... # List of data quality attributes
    properties:
      - id: txn_ref_dt_prop
        name: txn_ref_dt
        businessName: transaction reference date
        logicalType: date
        physicalType: date
        description: null
        partitioned: true
        partitionKeyPosition: 1
        criticalDataElement: false
        tags: []
        classification: public
        transformSourceObjects:
          - table_name_1
          - table_name_2
          - table_name_3
        transformLogic: sel t1.txn_dt as txn_ref_dt from table_name_1 as t1, table_name_2 as t2, table_name_3 as t3 where t1.txn_dt=date-3
        transformDescription: Defines the logic in business terms.
        examples:
          - 2022-10-03
          - 2020-01-28
      - id: rcvr_id_prop
        name: rcvr_id
        primaryKey: true
        primaryKeyPosition: 1
        businessName: receiver id
        logicalType: string
        physicalType: varchar(18)
        required: false
        description: A description for column rcvr_id.
        partitioned: false
        partitionKeyPosition: -1
        criticalDataElement: false
        tags: []
        classification: restricted
        encryptedName: enc_rcvr_id
      - id: rcvr_cntry_code_prop
        name: rcvr_cntry_code
        primaryKey: false
        primaryKeyPosition: -1
        businessName: receiver country code
        logicalType: string
        physicalType: varchar(2)
        required: false
        description: null
        partitioned: false
        partitionKeyPosition: -1
        criticalDataElement: false
        tags: []
        classification: public
        authoritativeDefinitions:
          - url: https://zeenea.app/asset/742b358f-71a5-4ab1-bda4-dcdba9418c25
            type: businessDefinition
          - url: https://github.com/myorg/myrepo
            type: transformationImplementation
          - url: jdbc:postgresql://localhost:5432/adventureworks/tbl_1/rcvr_cntry_code
            type: implementation
        encryptedName: rcvr_cntry_code_encrypted